executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT300to500_TuneCP5//QCD_HT300to500_TuneCP5_19.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT300to500_TuneCP5//QCD_HT300to500_TuneCP5_19.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT300to500_TuneCP5//QCD_HT300to500_TuneCP5_19.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT300to500_TuneCP5//QCD_HT300to500_TuneCP5_19.log
+JobFlavour = "testmatch"
queue
