executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/WJetsToQQ/nanov9/WJetsToQQ_HT-200to400_TuneCP5//WJetsToQQ_HT-200to400_TuneCP5_3.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/WJetsToQQ/nanov9/WJetsToQQ_HT-200to400_TuneCP5//WJetsToQQ_HT-200to400_TuneCP5_3.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/WJetsToQQ/nanov9/WJetsToQQ_HT-200to400_TuneCP5//WJetsToQQ_HT-200to400_TuneCP5_3.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/WJetsToQQ/nanov9/WJetsToQQ_HT-200to400_TuneCP5//WJetsToQQ_HT-200to400_TuneCP5_3.log
+JobFlavour = "testmatch"
queue
