executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/QCD/nanov9/QCD_HT1000to1500_TuneCP5//QCD_HT1000to1500_TuneCP5_30.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/QCD/nanov9/QCD_HT1000to1500_TuneCP5//QCD_HT1000to1500_TuneCP5_30.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/QCD/nanov9/QCD_HT1000to1500_TuneCP5//QCD_HT1000to1500_TuneCP5_30.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/QCD/nanov9/QCD_HT1000to1500_TuneCP5//QCD_HT1000to1500_TuneCP5_30.log
+JobFlavour = "testmatch"
queue
