executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT100to200_TuneCP5//QCD_HT100to200_TuneCP5_95.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT100to200_TuneCP5//QCD_HT100to200_TuneCP5_95.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT100to200_TuneCP5//QCD_HT100to200_TuneCP5_95.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT100to200_TuneCP5//QCD_HT100to200_TuneCP5_95.log
+JobFlavour = "testmatch"
queue
