executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT100to200_TuneCP5//QCD_HT100to200_TuneCP5_101.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT100to200_TuneCP5//QCD_HT100to200_TuneCP5_101.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT100to200_TuneCP5//QCD_HT100to200_TuneCP5_101.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT100to200_TuneCP5//QCD_HT100to200_TuneCP5_101.log
+JobFlavour = "testmatch"
queue
