executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M1200_13TeV_TuneCP5//ZpToHGamma_M1200_13TeV_TuneCP5_3.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M1200_13TeV_TuneCP5//ZpToHGamma_M1200_13TeV_TuneCP5_3.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M1200_13TeV_TuneCP5//ZpToHGamma_M1200_13TeV_TuneCP5_3.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M1200_13TeV_TuneCP5//ZpToHGamma_M1200_13TeV_TuneCP5_3.log
+JobFlavour = "testmatch"
queue
