executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/GJets_2018_nanov7/GJets_HT-600ToInf_TuneCP5//GJets_HT-600ToInf_TuneCP5_19.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/GJets_2018_nanov7/GJets_HT-600ToInf_TuneCP5//GJets_HT-600ToInf_TuneCP5_19.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/GJets_2018_nanov7/GJets_HT-600ToInf_TuneCP5//GJets_HT-600ToInf_TuneCP5_19.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/GJets_2018_nanov7/GJets_HT-600ToInf_TuneCP5//GJets_HT-600ToInf_TuneCP5_19.log
+JobFlavour = "testmatch"
queue
