executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT2000toInf_TuneCP5//QCD_HT2000toInf_TuneCP5_24.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT2000toInf_TuneCP5//QCD_HT2000toInf_TuneCP5_24.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT2000toInf_TuneCP5//QCD_HT2000toInf_TuneCP5_24.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT2000toInf_TuneCP5//QCD_HT2000toInf_TuneCP5_24.log
+JobFlavour = "testmatch"
queue
