executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT500to700_TuneCP5//QCD_HT500to700_TuneCP5_12.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT500to700_TuneCP5//QCD_HT500to700_TuneCP5_12.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT500to700_TuneCP5//QCD_HT500to700_TuneCP5_12.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT500to700_TuneCP5//QCD_HT500to700_TuneCP5_12.log
+JobFlavour = "testmatch"
queue
