executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/WJetsToQQ/nanov9/WJetsToQQ_HT-600to800_TuneCP5//WJetsToQQ_HT-600to800_TuneCP5_29.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/WJetsToQQ/nanov9/WJetsToQQ_HT-600to800_TuneCP5//WJetsToQQ_HT-600to800_TuneCP5_29.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/WJetsToQQ/nanov9/WJetsToQQ_HT-600to800_TuneCP5//WJetsToQQ_HT-600to800_TuneCP5_29.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/WJetsToQQ/nanov9/WJetsToQQ_HT-600to800_TuneCP5//WJetsToQQ_HT-600to800_TuneCP5_29.log
+JobFlavour = "testmatch"
queue
