executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/GJets_2018_nanov7/GJets_HT-400To600_TuneCP5//GJets_HT-400To600_TuneCP5_0.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/GJets_2018_nanov7/GJets_HT-400To600_TuneCP5//GJets_HT-400To600_TuneCP5_0.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/GJets_2018_nanov7/GJets_HT-400To600_TuneCP5//GJets_HT-400To600_TuneCP5_0.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/GJets_2018_nanov7/GJets_HT-400To600_TuneCP5//GJets_HT-400To600_TuneCP5_0.log
+JobFlavour = "testmatch"
queue
