executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M3500_13TeV_TuneCP5//ZpToHGamma_M3500_13TeV_TuneCP5_5.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M3500_13TeV_TuneCP5//ZpToHGamma_M3500_13TeV_TuneCP5_5.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M3500_13TeV_TuneCP5//ZpToHGamma_M3500_13TeV_TuneCP5_5.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M3500_13TeV_TuneCP5//ZpToHGamma_M3500_13TeV_TuneCP5_5.log
+JobFlavour = "testmatch"
queue
