executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/QCD/nanov9/QCD_HT2000toInf_TuneCP5//QCD_HT2000toInf_TuneCP5_28.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/QCD/nanov9/QCD_HT2000toInf_TuneCP5//QCD_HT2000toInf_TuneCP5_28.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/QCD/nanov9/QCD_HT2000toInf_TuneCP5//QCD_HT2000toInf_TuneCP5_28.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/QCD/nanov9/QCD_HT2000toInf_TuneCP5//QCD_HT2000toInf_TuneCP5_28.log
+JobFlavour = "testmatch"
queue
