executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT200to300_TuneCP5//QCD_HT200to300_TuneCP5_32.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT200to300_TuneCP5//QCD_HT200to300_TuneCP5_32.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT200to300_TuneCP5//QCD_HT200to300_TuneCP5_32.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT200to300_TuneCP5//QCD_HT200to300_TuneCP5_32.log
+JobFlavour = "testmatch"
queue
