executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZJetsToQQ/nanov9/ZJetsToQQ_HT-600to800_TuneCP5//ZJetsToQQ_HT-600to800_TuneCP5_41.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZJetsToQQ/nanov9/ZJetsToQQ_HT-600to800_TuneCP5//ZJetsToQQ_HT-600to800_TuneCP5_41.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZJetsToQQ/nanov9/ZJetsToQQ_HT-600to800_TuneCP5//ZJetsToQQ_HT-600to800_TuneCP5_41.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZJetsToQQ/nanov9/ZJetsToQQ_HT-600to800_TuneCP5//ZJetsToQQ_HT-600to800_TuneCP5_41.log
+JobFlavour = "testmatch"
queue
