executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZJetsToQQ/nanov9/ZJetsToQQ_HT-600to800_TuneCP5//ZJetsToQQ_HT-600to800_TuneCP5_15.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZJetsToQQ/nanov9/ZJetsToQQ_HT-600to800_TuneCP5//ZJetsToQQ_HT-600to800_TuneCP5_15.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZJetsToQQ/nanov9/ZJetsToQQ_HT-600to800_TuneCP5//ZJetsToQQ_HT-600to800_TuneCP5_15.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZJetsToQQ/nanov9/ZJetsToQQ_HT-600to800_TuneCP5//ZJetsToQQ_HT-600to800_TuneCP5_15.log
+JobFlavour = "testmatch"
queue
