executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M3000_13TeV_TuneCP5//ZpToHGamma_M3000_13TeV_TuneCP5_2.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M3000_13TeV_TuneCP5//ZpToHGamma_M3000_13TeV_TuneCP5_2.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M3000_13TeV_TuneCP5//ZpToHGamma_M3000_13TeV_TuneCP5_2.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/logs/mc/2018/ZpToHGamma/nanov7/ZpToHGamma_M3000_13TeV_TuneCP5//ZpToHGamma_M3000_13TeV_TuneCP5_2.log
+JobFlavour = "testmatch"
queue
