executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT700to1000_TuneCP5//QCD_HT700to1000_TuneCP5_41.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT700to1000_TuneCP5//QCD_HT700to1000_TuneCP5_41.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT700to1000_TuneCP5//QCD_HT700to1000_TuneCP5_41.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT700to1000_TuneCP5//QCD_HT700to1000_TuneCP5_41.log
+JobFlavour = "testmatch"
queue
