executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT700to1000_TuneCP5//QCD_HT700to1000_TuneCP5_26.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT700to1000_TuneCP5//QCD_HT700to1000_TuneCP5_26.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT700to1000_TuneCP5//QCD_HT700to1000_TuneCP5_26.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT700to1000_TuneCP5//QCD_HT700to1000_TuneCP5_26.log
+JobFlavour = "testmatch"
queue
