executable = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT1000to1500_TuneCP5//QCD_HT1000to1500_TuneCP5_40.sh
universe = vanilla
output = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT1000to1500_TuneCP5//QCD_HT1000to1500_TuneCP5_40.out
error = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT1000to1500_TuneCP5//QCD_HT1000to1500_TuneCP5_40.err
log = /home/pku/fudawei/GitRepo/NanoAnalysis/checkoutNano/condor_jobs/QCD_2018_nanov7/QCD_HT1000to1500_TuneCP5//QCD_HT1000to1500_TuneCP5_40.log
+JobFlavour = "testmatch"
queue
